//[example_output
> example76
Running 3 test cases...
test.cpp(24): error: in "test_case3": check false has failed

*** 1 failure detected in test module "example76"

> example76 --list_content
test_case1
test_case3
test_case4
//]